#!/bin/bash
set -euo pipefail

# our type
type="${1}"

function start_lexer() {
  windows=(ssh-sessions cur-proj misc)
  tmux new-session -s "${session_name}" -n "ops-infra" -d
  for ((i = 0; i < ${#windows[@]}; i++)); do
    index=$(($i+2))
    tmux new-window -t "${session_name}:${index}" -n "${windows[$i]}"
  done
  
  # run our bootstrap commands for ops-infra
  tmux select-window -t "${session_name}:1"
  tmux send -t "${session_name}:1" "sleep 1 && cd ops-infra" ENTER 
  tmux send -t "${session_name}:1" vim ENTER
  tmux split-window -h
  tmux send -t "${session_name}:1" "cd ops-infra && git status" ENTER
  tmux split-window -v
  tmux send -t "${session_name}:1" "cd ops-infra && sleep 5 && make -j 8 all" ENTER
  tmux select-pane -L
  sleep 1
  tmux attach-session -t "${session_name}:1"
}

function start_lucas() {
  windows=(project misc)
  tmux new-session -s "${session_name}" -n "zoidberg" -d
  for ((i = 0; i < ${#windows[@]}; i++)); do
    index=$(($i+2))
    tmux new-window -t "${session_name}:${index}" -n "${windows[$i]}"
  done

  # run our bootstrap commands for at home
  tmux select-window -t "${session_name}:1"
  tmux send -t "${session_name}:1" "ssh zoidberg" ENTER 
  tmux attach-session -t "${session_name}:1"
}

function start_default() {
  windows=(default)
  tmux new-session -s "${session_name}" -n "default" -d
  tmux attach-session -t "${session_name}:1"
}

# select the correct parameters depending on what we want to do
if [[ ${type} == "lexer" ]]; then
  cd ${HOME}/Encrypted/lexer/repos/ 
  session_name="ops"
  start_lexer
elif [[ ${type} == "lucas" ]]; then
  cd ${HOME}/Encrypted/lucas/
  session_name="dev"
  start_lucas
else
  cd ${HOME}
  session_name="default"
  start_default
fi

